"use client";

import React, { createContext, useContext, useState, ReactNode } from 'react';
import {
  MOCK_RECOMMENDATIONS,
  MOCK_CHAT_HISTORY,
  MOCK_WORKFLOWS,
  MOCK_AUTOMATION_LOGS,
  DEFAULT_SETTINGS,
  MOCK_ACTIVITIES,
  MOCK_UPCOMING_TASKS,
  AIAgent,
  MOCK_AGENTS,
  ChatThread,
  Workflow,
  AutomationLog,
  Notification
} from '../data/mockData';

interface Recommendation {
  id: string;
  title: string;
  agent: string;
  description: string;
  urgency: string;
  actionLabel: string;
  category: string;
  impact: string;
  approved: boolean;
}

interface StoreContextProps {
  recommendations: Recommendation[];
  approveRecommendation: (id: string) => void;
  chatThreads: ChatThread[];
  activeThreadId: string;
  setActiveThreadId: (id: string) => void;
  sendChatMessage: (text: string) => void;
  createNewChat: (title: string) => string;
  workflows: typeof MOCK_WORKFLOWS;
  toggleWorkflow: (id: string) => void;
  addWorkflow: (wf: Omit<Workflow, 'id' | 'lastRun' | 'successRate'>) => void;
  logs: typeof MOCK_AUTOMATION_LOGS;
  addLog: (log: AutomationLog) => void;
  notifications: Notification[];
  dismissNotification: (id: string) => void;
  approveNotificationAction: (id: string) => void;
  settings: typeof DEFAULT_SETTINGS;
  updateSettings: (section: string, data: Partial<typeof DEFAULT_SETTINGS[keyof typeof DEFAULT_SETTINGS]>) => void;
  sidebarOpen: boolean;
  setSidebarOpen: (open: boolean) => void;
  agents: AIAgent[];
  updateAgentStatus: (id: string, status: 'idle' | 'running' | 'thinking') => void;
  activities: typeof MOCK_ACTIVITIES;
  addActivity: (text: string, type: string) => void;
  upcomingTasks: typeof MOCK_UPCOMING_TASKS;
  dismissTask: (id: string) => void;
}

const StoreContext = createContext<StoreContextProps | undefined>(undefined);

export const StoreProvider = ({ children }: { children: ReactNode }) => {
  const [recommendations, setRecommendations] = useState<Recommendation[]>(MOCK_RECOMMENDATIONS);
  const [chatThreads, setChatThreads] = useState<ChatThread[]>(MOCK_CHAT_HISTORY);
  const [activeThreadId, setActiveThreadId] = useState<string>(MOCK_CHAT_HISTORY[0]?.id || '');
  const [workflows, setWorkflows] = useState(MOCK_WORKFLOWS);
  const [logs, setLogs] = useState(MOCK_AUTOMATION_LOGS);
  const [agents, setAgents] = useState<AIAgent[]>(MOCK_AGENTS);
  const [activities, setActivities] = useState(MOCK_ACTIVITIES);
  const [upcomingTasks, setUpcomingTasks] = useState(MOCK_UPCOMING_TASKS);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [settings, setSettings] = useState(DEFAULT_SETTINGS);

  // Notifications State (combines warnings, alerts, approvals)
  const [notifications, setNotifications] = useState<Notification[]>([
    { id: 'notif-1', title: 'Critical Low Stock: Model-B Sensor', desc: 'Stock is currently 12 units (safety limit: 30). Restock required.', type: 'warning', category: 'Inventory', time: '10 mins ago', actionRequired: true, approved: false },
    { id: 'notif-2', title: 'Invoice Approval Required: #INV-4920', desc: 'Invoice amount of $12,400 from Acme Supplies matches purchase authorization.', type: 'approval', category: 'Finance', time: '15 mins ago', actionRequired: true, approved: false },
    { id: 'notif-3', title: 'Security Alert: New API Key created', desc: 'New read-only production token generated by People Sync Agent.', type: 'alert', category: 'System', time: '1 hour ago', actionRequired: false },
    { id: 'notif-4', title: 'Marketing Campaign ROI Exceeded', desc: 'LinkedIn Enterprise Campaign reached 3.5x ROI threshold set in marketing targets.', type: 'alert', category: 'Marketing', time: '3 hours ago', actionRequired: false }
  ]);

  const approveRecommendation = (id: string) => {
    setRecommendations(prev =>
      prev.map(rec => (rec.id === id ? { ...rec, approved: true } : rec))
    );
    const rec = recommendations.find(r => r.id === id);
    if (rec) {
      addActivity(`Approved AI recommendation: "${rec.title}"`, rec.category.toLowerCase());
    }
  };

  const sendChatMessage = (text: string) => {
    if (!activeThreadId) return;

    // Add user message
    setChatThreads(prev =>
      prev.map(thread => {
        if (thread.id === activeThreadId) {
          return {
            ...thread,
            messages: [...thread.messages, { sender: 'user', text }]
          };
        }
        return thread;
      })
    );

    // Simulate Agent typing response
    setTimeout(() => {
      let replyText = "I have processed your query. Let me analyze that for you.";
      if (text.toLowerCase().includes('cash flow') || text.toLowerCase().includes('q3')) {
        replyText = "Based on our Q2 financial results, the Finance Agent forecasts a **$520,000 inflow** in Q3, driven by a 14.2% growth in ARR. Operational expenditure is projected to increase by 8% due to server capacity additions. Net Cash flow will remain positive at **+$140,000** monthly.";
      } else if (text.toLowerCase().includes('marketing') || text.toLowerCase().includes('roi')) {
        replyText = "Our LinkedIn campaigns are performing at **3.5x ROI**, while Google Ads search campaigns are at **1.2x**. I recommend pausing the Google campaigns and redirecting that budget into Meta or LinkedIn for better conversion rates.";
      } else if (text.toLowerCase().includes('stock') || text.toLowerCase().includes('inventory')) {
        replyText = "Model-B is low (12 units remaining). Model-Y is critical (4 units remaining). I have generated draft Purchase Orders for both suppliers (TechParts Corp and PowerLine Ltd) waiting for your signoff in the Finance/Inventory dashboard.";
      } else if (text.toLowerCase().includes('warning') || text.toLowerCase().includes('system')) {
        replyText = "We have 2 critical notices: 1) Low Stock alerts for Model-B & Model-Y; 2) Invoice INV-4920 from Acme Supplies is awaiting approval.";
      }

      setChatThreads(prev =>
        prev.map(thread => {
          if (thread.id === activeThreadId) {
            return {
              ...thread,
              messages: [...thread.messages, { sender: 'agent', text: replyText }]
            };
          }
          return thread;
        })
      );
      addActivity('AI Agent responded in chat thread.', 'ceo');
    }, 1000);
  };

  const createNewChat = (title: string) => {
    const newId = `c-${Date.now()}`;
    const newThread: ChatThread = {
      id: newId,
      title: title || `New Discussion (${chatThreads.length + 1})`,
      messages: [{ sender: 'agent', text: 'Hello! I am the AI Operating System. How can I assist you with your business today?' }]
    };
    setChatThreads(prev => [newThread, ...prev]);
    setActiveThreadId(newId);
    return newId;
  };

  const toggleWorkflow = (id: string) => {
    setWorkflows(prev =>
      prev.map(wf => (wf.id === id ? { ...wf, status: wf.status === 'Active' ? 'Paused' : 'Active' } : wf))
    );
    const wf = workflows.find(w => w.id === id);
    if (wf) {
      addActivity(`Toggled workflow: "${wf.name}" to ${wf.status === 'Active' ? 'Paused' : 'Active'}.`, 'operations');
    }
  };

  const addWorkflow = (wf: Omit<Workflow, 'id' | 'lastRun' | 'successRate'>) => {
    setWorkflows(prev => [...prev, { ...wf, id: `wf-${Date.now()}`, lastRun: 'Never', successRate: '100%' }]);
    addActivity(`Created new automation workflow: "${wf.name}"`, 'operations');
  };

  const addLog = (log: AutomationLog) => {
    setLogs(prev => [log, ...prev]);
  };

  const dismissNotification = (id: string) => {
    setNotifications(prev => prev.filter(n => n.id !== id));
  };

  const approveNotificationAction = (id: string) => {
    setNotifications(prev =>
      prev.map(n => (n.id === id ? { ...n, approved: true, actionRequired: false } : n))
    );
    const notif = notifications.find(n => n.id === id);
    if (notif) {
      addActivity(`Approved notification action: "${notif.title}"`, notif.category.toLowerCase());
    }
  };

  const updateSettings = (section: string, data: Partial<typeof DEFAULT_SETTINGS[keyof typeof DEFAULT_SETTINGS]>) => {
    setSettings(prev => ({
      ...prev,
      [section]: { ...prev[section as keyof typeof DEFAULT_SETTINGS], ...data }
    }));
    addActivity(`Updated configuration settings for ${section}.`, 'ceo');
  };

  const updateAgentStatus = (id: string, status: 'idle' | 'running' | 'thinking') => {
    setAgents(prev =>
      prev.map(a => (a.id === id ? { ...a, status } : a))
    );
  };

  const addActivity = (text: string, type: string) => {
    const newAct = {
      id: `act-${Date.now()}`,
      text,
      time: 'Just now',
      type
    };
    setActivities(prev => [newAct, ...prev]);
  };

  const dismissTask = (id: string) => {
    setUpcomingTasks(prev => prev.filter(t => t.id !== id));
  };

  return (
    <StoreContext.Provider
      value={{
        recommendations,
        approveRecommendation,
        chatThreads,
        activeThreadId,
        setActiveThreadId,
        sendChatMessage,
        createNewChat,
        workflows,
        toggleWorkflow,
        addWorkflow,
        logs,
        addLog,
        notifications,
        dismissNotification,
        approveNotificationAction,
        settings,
        updateSettings,
        sidebarOpen,
        setSidebarOpen,
        agents,
        updateAgentStatus,
        activities,
        addActivity,
        upcomingTasks,
        dismissTask
      }}
    >
      {children}
    </StoreContext.Provider>
  );
};

export const useClientStore = () => {
  const context = useContext(StoreContext);
  if (!context) {
    throw new Error('useClientStore must be used within a StoreProvider');
  }
  return context;
};
